INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Cuenta con servicios higiénicos, de uso individual o colectivo.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Si los baños se encuentran en salas de baño del público, los que utilizan los trabajadores (as) son de uso exclusivo')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Cuenta con servicios higiénicos independientes y separados por sexo.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Mantiene los servicios higiénicos en buen estado de limpieza y/o funcionamiento.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Dispone de comedor, para los trabajadores que se vean precisados a consumir alimentos en el lugar de trabajo.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('El comedor cuenta con las condiciones mínimas exigibles: mesas y sillas con cubierta de material lavable, lavaplatos, cocinilla y separado de fuentes de contaminación (basuras, polvos, etc.).')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Mantiene buenas condiciones de orden, aseo e iluminación en escaleras y estas cuentan con barandas.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Cuenta con señalización visible y permanente, indicando las vías de escape y zonas de seguridad ante emergencias.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Mantiene protegidos los circuitos y equipos eléctricos mediante protector diferencial.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Mantiene en buen estado los conductores eléctricos, enchufes, interruptores, equipos de iluminación, ventilación, calefacción.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Mantiene extintores de incendio adecuados al riesgo a cubrir.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Realiza mantención preventiva de extintores por lo menos una vez al año (revisión técnica).')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Ubica extintores en sitios de fácil acceso y claramente identificables.')
INSERT INTO "PRUEBALOCAL"."CONDICION" (NOM_CONDICION) VALUES ('Instruye y entrena a los trabajadores sobre la manera de usar los extintores en caso de emergencia.')

INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('EXPLOTACIÓN DE MINAS Y CANTERAS N.C.P.')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('EXTRACCIÓN Y PROCESAMIENTO DE LITIO')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('FABRICACIÓN DE VIDRIO PLANO')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('	FUNDICIÓN DE HIERRO Y ACERO')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('FABRICACIÓN DE EQUIPO DE IRRADIACIÓN Y EQUIPO ELECTRÓNICO DE USO MÉDICO Y TERAPÉUTICO')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('FABRICACIÓN DE PILAS, BATERÍAS Y ACUMULADORES')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('FABRICACIÓN DE HERRAMIENTAS DE MANO MOTORIZADAS')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('FABRICACIÓN DE AERONAVES, NAVES ESPACIALES Y MAQUINARIA CONEXA')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('EXTRACCIÓN DE GAS NATURAL')
INSERT INTO "PRUEBALOCAL"."RUBRO" (NOM_RUBRO) VALUES ('EXPLOTACIÓN DE MATADEROS DE AVES Y DE OTROS TIPOS DE ANIMALES N.C.P.')


INSERT INTO "PRUEBALOCAL"."TIPO_SOLICITUD" (NOM_SOLICITUD) VALUES ('Asesoría')
INSERT INTO "PRUEBALOCAL"."TIPO_SOLICITUD" (NOM_SOLICITUD) VALUES ('Capacitación')
INSERT INTO "PRUEBALOCAL"."TIPO_SOLICITUD" (NOM_SOLICITUD) VALUES ('Visita')
INSERT INTO "PRUEBALOCAL"."TIPO_SOLICITUD" (NOM_SOLICITUD) VALUES ('Modificar checklist')

INSERT INTO "PRUEBALOCAL"."ESTADO_ACTIVIDAD" (NOM_EST_ACTIVIDAD) VALUES ('Pendiente')
INSERT INTO "PRUEBALOCAL"."ESTADO_ACTIVIDAD" (NOM_EST_ACTIVIDAD) VALUES ('Listo')

INSERT INTO "PRUEBALOCAL"."ESTADO_CONTRATO" (NOM_ESTADO_CONTRATO) VALUES ('Activo')
INSERT INTO "PRUEBALOCAL"."ESTADO_CONTRATO" (NOM_ESTADO_CONTRATO) VALUES ('Inactivo')


INSERT INTO "PRUEBALOCAL"."AUTH_GROUP" (NAME) VALUES (N'Profesional')
INSERT INTO "PRUEBALOCAL"."AUTH_GROUP" (NAME) VALUES (N'Cliente')
INSERT INTO "PRUEBALOCAL"."AUTH_GROUP" (NAME) VALUES (N'Administrador')

